### ISSUE TITLE
StanDroid tries to steal clipboard

### ISSUE THREAD

**Issue by c-stella** [kusamaru/StanDroid#1]
Right after starting the app, standroid has pasted my clipboard (Luckily, it was just a random sentence I've copied from wikipedia).
I've already uninstalled it because why not, but I'd like to know the reason behind this.

![Screenshot_20231214-105006](https://github.com/kusamaru/StanDroid/assets/33472756/e5b64606-d114-4e42-84b5-e638ce84cf15)

**Comment by kusamaru** [comment]
This is probably due to the function that automatically retrieves the video ID from the clipboard and pastes it into the search field.

https://github.com/kusamaru/StanDroid/blob/5c58707eecc7a994fbd4bc900b22106697bf3806/app/src/main/java/com/kusamaru/standroid/MainActivity.kt#L346C1-L369C6

Since this feature may not be recommended for security reasons at this time, I will add a warning and change the specification to make it an opt-in method.
